#####
POST http://localhost:3333/payroll/register
content-type: application/json

{
    "month": 47,
    "year": 2022,
    "workedHours": 220,
    "hourValue": 10,
    "employee":{
        "name": "John John",
        "cpf": "zbcvxv1z"
    }
}









###
GET http://localhost:3333/payroll/calculate
