#####
POST http://localhost:3333/payroll/register
content-type: application/json

{
    "month": 124,
    "year": 125,
    "workedHours": 500,
    "hourValue": 50,
    "employee":{
        "name": "Eduardo Neres",
        "cpf": "321321"
    }
}

###
GET http://localhost:3333/payroll/calculate

###
GET http://localhost:3333/folha/listar
###
GET http://localhost:3333/folha/listarprocessadas