#####
POST http://localhost:3333/folha/cadastrar
content-type: application/json

{
    "month": 987,
    "year": 1324,
    "workedHours": 500,
    "hourValue": 50,
    "employee":{
        "name": "Eduardo Neres",
        "cpf": "32213213213"
    }
}

###
GET http://localhost:3333/folha/calcular

###
GET http://localhost:3333/folha/listar
###
GET http://localhost:3333/folha/listarprocessadas