
###
GET http://localhost:3334/payroll/list
###
GET http://localhost:3334/payroll/list/123456789/12/2022
###
GET http://localhost:3334/payroll/list/123456789
###
GET http://localhost:3334/payroll/list/12/2022